reference_db/app/routes/intensities/__init__.py
from flask import Blueprint

bp = Blueprint('intensities', __name__)

from app.routes.intensities import routes

reference_db/app/routes/intensities/routes.py
import sqlalchemy.exc
from flask import render_template, request, url_for, flash, redirect
from flask_login import login_required

from app.forms.forms import IntensityForm
from app.routes.intensities import bp

from app.models.model import Intensity

from app.extensions import db

@bp.route('/')
@login_required
def index():
    """
        Index page for intensities, only accessible for logged in users. Allowing the user to add, edit and delete intensities

    Returns:
        rendered template of the index page, with all the intensities
    """
    intensities = db.session.query(Intensity).all()
    return render_template('resources/intensities/index.html', intensities=intensities)


@bp.route('/new', methods=['GET'])
@login_required
def new():
    """
        Create page for intensities, only accessible for logged in users

    Returns:
        rendered template of the new page, with the form for creating a new intensity
    """
    form = IntensityForm()
    return render_template('resources/intensities/new.html', form=form)


@bp.route('/new', methods=['POST'])
@login_required
def new_post():
    """
        Creates a new intensity, only accessible for logged in users

    Returns:
        based on the validation of the form, either redirects to this resources index page or renders
        the new page again with validation errors (WTForms) or integrity errors (SQL constraints)
    """
    # convert request.form to form object
    form = IntensityForm(request.form)
    # if the form is not valid, redirect to the new page and pass the values from the form
    if not form.validate():
        return render_template('resources/intensities/new.html', form=form)
    # if the form is valid, create a new slide and redirect to the index page
    else:
        # if unique constraint is violated, inform the user
        try:
            intensity = Intensity(shorthand=form.shorthand.data, description=form.description.data)
            db.session.add(intensity)
            db.session.commit()
            return redirect(url_for('intensities.index'))
        except sqlalchemy.exc.IntegrityError:
            flash('Diese Bezeichnung existiert bereits', 'danger')
            return render_template('resources/intensities/new.html', form=form)


@bp.route('/<intensity_id>/edit', methods=['GET'])
@login_required
def edit(intensity_id):
    """
        Edit page for intensities, only accessible for logged in users

    Args:
        intensity_id (int): id of the intensity to edit, passed as a parameter in the url

    Returns:
        rendered template of the edit page, with the form for editing an intensity
    """
    intensity = db.session.query(Intensity).filter(Intensity.id == intensity_id).first()
    form = IntensityForm(obj=intensity)
    return render_template('resources/intensities/edit.html', form=form)


@bp.route('/<intensity_id>/edit', methods=['POST'])
@login_required
def edit_post(intensity_id):
    """
        Edits the intensity, only accessible for logged in users

    Args:
        intensity_id (int): id of the intensity to edit, passed as a parameter in the url

    Returns:
        based on the validation of the form, either redirects to this resources index page or
        renders the Edit page again with validation errors (WTForms) or integrity errors (SQL constraints)
    """

    # convert request.form to form object
    form = IntensityForm(request.form)
    # if the form is not valid, redirect to the new page and pass the values from the form
    if not form.validate():
        return render_template('resources/intensities/edit.html', form=form)
    # if the form is valid, create a new slide and redirect to the index page
    else:
        # if unique constraint is violated, inform the user
        try:
            intensity = db.session.query(Intensity).filter(Intensity.id == intensity_id).first()
            intensity.shorthand = form.shorthand.data
            intensity.description = form.description.data
            db.session.add(intensity)
            db.session.commit()
            return redirect(url_for('intensities.index'))
        except sqlalchemy.exc.IntegrityError:
            flash('Diese Bezeichnung existiert bereits', 'danger')
            return render_template('resources/intensities/edit.html', form=form)


@bp.route('/<intensity_id>/delete', methods=['GET'])
@login_required
def delete(intensity_id):
    """
        Deletes the intensity only if not used in a peak, only accessible for logged in users

    Args:
        intensity_id (int): id of the intensity to delete, passed as a parameter in the url

    Returns:
        redirects to the index page, with a flash message based on the success of the deletion
    """
    try:
        intensity = db.session.query(Intensity).filter(Intensity.id == intensity_id).first()
        db.session.delete(intensity)
        db.session.commit()
        return redirect(url_for('intensities.index'))
    except sqlalchemy.exc.IntegrityError:
        flash('Diese Intensität wird noch verwendet und kann daher nicht gelöscht werden', 'danger')
        return redirect(url_for('intensities.index'))
    except:
        flash('Intensität konnte nicht gelöscht werden. Probieren Sie es später erneut', 'danger')
        return redirect(url_for('intensities.index'))

reference_db/app/templates/resources/intensities/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3 content">

    <a class="icon-link icon-link-hover mb-2"
       style="--bs-icon-link-transform: translate3d(-.125rem, 0, 0); --bs-link-color-rgb: 97,100,102;"
       href="{{ url_for('intensities.index') }}">
        <i class="bi bi-arrow-left mb-auto"></i>
        Zurück
    </a>

    <h1>Bearbeiten <b><em>Intensität</em></b></h1>
    {% include 'includes/errors.html' %}
    <form method="POST" novalidate class="row g-3">
        {{form.csrf_token}}
        <div class="mb-3 col-md-6">
            {{ form.shorthand.label(class="form-label") }}
            {{ form.shorthand(class="form-control", placeholder="vs")}}
            {% if form.shorthand.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.shorthand.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="mb-3 col-md-6">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control", placeholder="vs")}}
            {% if form.description.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.description.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Speichern</button>
        </div>
    </form>
</div>
{% endblock %}

reference_db/app/templates/resources/intensities/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3 content">
    {% include 'includes/backToStart.html' %}
    {% include 'includes/errors.html' %}
    <div class="row">
        <div class="col-12 col-md-6 d-flex align-items-center justify-content-start">
            <h1>Übersicht <b><em>Intensitäten</em></b></h1>
        </div>
        <div class="col-12 col-md-6 d-flex align-items-center justify-content-start justify-content-md-end">
            <a type="button" class="btn btn-outline-success btn-sm" href="{{ url_for('intensities.new') }}"><i
                    class="bi bi-plus-lg"></i>
                Neue Intensität erstellen
            </a>
        </div>
    </div>
    {% if intensities|length<=0 %}
    <h4>Es sind noch keine Intensitäten hinterlegt</h4>
    {% else %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Abkürzung</th>
            <th>Beschreibung</th>
            <th>Aktionen</th>
        </tr>
        </thead>
        <tbody>
        {% for intensity in intensities %}
        <tr>
            <td>{{ intensity.shorthand }}</td>
            <td>{{ intensity.description }}</td>
            <td>
                <a type="button" class="btn btn-outline-primary btn-sm"
                   href="{{ url_for('intensities.edit', intensity_id=intensity.id) }}"><i class="bi bi-pencil-fill"></i>
                    Bearbeiten</a>
                <a type="button" class="btn btn-outline-danger btn-sm"
                   href="{{ url_for('intensities.delete', intensity_id=intensity.id) }}"><i class="bi bi-trash-fill"></i> Löschen</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{% endblock %}

reference_db/app/templates/resources/intensities/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3 content">

    <a class="icon-link icon-link-hover mb-2"
       style="--bs-icon-link-transform: translate3d(-.125rem, 0, 0); --bs-link-color-rgb: 97,100,102;"
       href="{{ url_for('intensities.index') }}">
        <i class="bi bi-arrow-left mb-auto"></i>
        Zurück
    </a>

    <h1>Erstellen <b><em>Intensität</em></b></h1>
    {% include 'includes/errors.html' %}
    <form method="POST" novalidate class="row g-3">
        {{form.csrf_token}}
        <div class="mb-3 col-md-6">
            {{ form.shorthand.label(class="form-label") }}
            {{ form.shorthand(class="form-control", placeholder="vs")}}
            {% if form.shorthand.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.shorthand.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="mb-3 col-md-6">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control", placeholder="very strong")}}
            {% if form.description.errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.description.errors %}
                <p class="mb-0">
                    {{ error }}
                </p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Erstellen</button>
        </div>
    </form>
</div>
{% endblock %}